### ISSUE TITLE
Add NAME to ARC files

### ISSUE THREAD

**Issue by sebdel** [sebdel/mra-tools-c#20]
- use the name or the MRA file to generate a NAME in the ARC file:

e.g. after: 
```mra -A scramble.mra```
The arc file should contain:

NAME=SCRAMBLE

**Comment by sebdel** [comment]
- this name is actually the setname if present.
- use this name to name the ROM file.

**Comment by gyurco** [comment]
Cool! Just finished the firmware part. Wasn't the merging exchanged? The add_name_to_arc_files branch should be merged to master, not vica-versa?

**Comment by gyurco** [comment]
As I see, name is written to the NAME=, not setname.
The rule should be:
name -> ARC filename
setname -> ROM filename, NAME= in ARC

**Comment by sebdel** [comment]
The merge from master was to get the CRC fix on this branch. I should have rebase probably.

**Comment by sebdel** [comment]
> setname -> ROM filename, NAME= in ARC

not exactly setname, but "first 8 chars of setname, in upper case", right ?

**Comment by gyurco** [comment]
Yes, that's even more precise.
