### ISSUE TITLE
Support multi zip attribute for ROM

### ISSUE THREAD

**Issue by sebdel** [sebdel/mra-tools-c#25]
Something like this: 
`<rom index="0" zip="amidar.zip|amidars.zip" md5="22506edd9fb15fc2f5608c0174217753" type="merged|split|nonmerged">`
- **zip** attribute should be read as a list of file names to source from when using **part crc** and **part name**.

While doing this, change the way **type** is parsed as well. It is not used at the moment but we never know.

**Comment by eubrunosilva** [comment]
drop the type... i think is useless now
