### ISSUE TITLE
Output folder is the same as the input folder, it should be the local one

### ISSUE THREAD

**Issue by jotego** [sebdel/mra-tools-c#27]
when calling mra like:
```
mra ../ffight.mra
```
The output ffight.rom will be located at ../ffight.rom instead of the expected current directory.

**Comment by sebdel** [comment]
I did it on purpose, I didn't know which one made more sense. So, let's say...
- revert to output to current dir by default
- add argument -O <output dir> ?

**Comment by eubrunosilva** [comment]
add argument :)
