### ISSUE TITLE
about values in parts

### ISSUE THREAD

**Issue by eubrunosilva** [sebdel/mra-tools-c#28]
Hi

because i don't know you are aware, some values can be hex or decimal:

you have here an example:
https://github.com/MiSTer-devel/Arcade-Arkanoid_MISTer/blob/master/releases/Arkanoid%20(unl.lives%2C%20slower).mra

patch offset here is in hex
<patch offset="0xBFFF">
and i dont know if its possible to have a decimal value in offset.

here offset and lenght are decimal
https://github.com/MiSTer-devel/Arcade-RallyX_MiSTer/blob/master/releases/New%20Rally-X.mra

In repeat is possible to have hex and decimal

hex example:
https://github.com/MiSTer-devel/Arcade-MCR3Scroll_MiSTer/blob/master/releases/Crater%20Raider.mra

decimal example:
https://github.com/MiSTer-devel/Arcade-MCR2_MiSTer/blob/master/releases/Domino%20Man.mra

**Comment by sebdel** [comment]
good point, thanks.
..and once again it's poorly thought out :(
I mean look at his (both hex of course):

```
<part crc="05803453" name="crsnd3.a10"/> 
<part repeat="0x6000">00</part>
```

**Comment by sebdel** [comment]
just leaving this here: 

offfset, length and repeat are now parsed using strtoul, which means:

1234 is decimal (ok)
0x1234 is hexa (sure)
0X1234 is hexa (neat)
01234 is octal (**WARNING**)

**Comment by eubrunosilva** [comment]
hum... octal i dont think it will be used...

**Comment by sebdel** [comment]
I know, it's a side effect of using the function strtoul, but it's really convenient so...

**Comment by jotego** [comment]
I have used octal in some retro cores. It is convenient sometimes.
