### ISSUE TITLE
Support MiSTer style interleaving 

### ISSUE THREAD

**Issue by sebdel** [sebdel/mra-tools-c#32]
- what we call **group**, they call **interleave**
- what we call **width**, they call **output**
- **map** is kind of like **pattern** but that will need some more analysis

TBD: Shall this replace **group** or be supported in addition to it?

**Comment by eubrunosilva** [comment]
i would support both...

group is mra comes from mist (if devs prefer group instead of interleave)
interleave if mra comes from mister
