### ISSUE TITLE
file path in windows

### ISSUE THREAD

**Issue by eubrunosilva** [sebdel/mra-tools-c#37]
in windows, with verbose, i get a "/" when i should have "\". Files are writen ok in filesystem (don't know if windows is converting the "/" to "\" or if this only happens in output to screen in verbose

example:

C:\MRA_Files\mra\SiDi>c:\mra_files\mra.exe -Avz c:\mra_files\nonmerged -O "C:\MRA_files\mra\SiDi\alternatives\Sinistar" "C:\MRA_files\mra\SiDi\alternatives\Sinistar\Sinistar (prototype version).mra"
Parsing C:\MRA_files\mra\SiDi\alternatives\Sinistar\Sinistar (prototype version).mra to C:\MRA_files\mra\SiDi\alternatives\Sinistar/sinistar.rom
zip include dirs: c:\mra_files\nonmerged/, ./
Creating ARC file C:\MRA_files\mra\SiDi\alternatives\Sinistar/Sinistar (prototype version).arc
Uncompressing zip file: c:\mra_files\nonmerged/sinistar.zip
Uncompressing zip file: c:\mra_files\nonmerged/sinistar1.zip
FILE            SIZE    CRC
----            ----    ---
decoder.4               512     E6631C23
decoder.6               512     83FAF25E
sinistar.01             4096    F6F3A22C
sinistar.02             4096    CAB3185C
sinistar.03             4096    1CE1B3CC
sinistar.04             4096    6DA632BA
sinistar.05             4096    B662E8FC
sinistar.06             4096    2306183D
sinistar.07             4096    E5DD918E
sinistar.08             4096    4785A787
sinistar.09             4096    50CB63AD
sinistar.10             4096    3D670417
sinistar.11             4096    3162BC50
sinistar.snd            4096    B82F4DDB
speech.ic4              4096    4B56A626
speech.ic5              4096    CF3B5FFD
speech.ic6              4096    FF8D2645
speech.ic7              4096    E1019568
decoder.4               512     E6631C23
decoder.6               512     83FAF25E
sinistar.02             4096    CAB3185C
sinistar.snd            4096    B82F4DDB
sinrev1.01              4096    3810D7B8
sinrev1.03              4096    7C984CA9
sinrev1.04              4096    CC6C4F24
sinrev1.05              4096    12285BFE
sinrev1.06              4096    7A675F35
sinrev1.07              4096    B0463243
sinrev1.08              4096    909040D4
sinrev1.09              4096    CC949810
sinrev1.10              4096    EA87A53F
sinrev1.11              4096    88D36E80
speech.ic4              4096    4B56A626
speech.ic5              4096    CF3B5FFD
speech.ic6              4096    FF8D2645
speech.ic7              4096    E1019568
part selected by CRC (3810D7B8)
writing 4096 bytes @ 00000000
part selected by CRC (CAB3185C)
writing 4096 bytes @ 00001000
part selected by CRC (7C984CA9)
writing 4096 bytes @ 00002000
part selected by CRC (CC6C4F24)
writing 4096 bytes @ 00003000
part selected by CRC (12285BFE)
writing 4096 bytes @ 00004000
part selected by CRC (7A675F35)
writing 4096 bytes @ 00005000
part selected by CRC (B0463243)
writing 4096 bytes @ 00006000
part selected by CRC (909040D4)
writing 4096 bytes @ 00007000
part selected by CRC (CC949810)
writing 4096 bytes @ 00008000
part selected by CRC (EA87A53F)
writing 4096 bytes @ 00009000
part selected by CRC (EA87A53F)
writing 4096 bytes @ 0000A000
part selected by CRC (88D36E80)
writing 4096 bytes @ 0000B000
part selected by CRC (B82F4DDB)
writing 4096 bytes @ 0000C000
writing 1024 bytes @ 0000D000
ce723cbcfea8010e69a0a4f25b421405        C:\MRA_files\mra\SiDi\alternatives\Sinistar/sinistar.rom
MD5s match! (ce723cbcfea8010e69a0a4f25b421405)
done!

**Comment by sebdel** [comment]
The libc we use for windows (from mingw) does the conversion itself. So this is "just" a cosmetic problem. I'll fix it eventually but it's nothing to worry about.

**Comment by eubrunosilva** [comment]
yes. software is working well but i want you to know this :)
