### ISSUE TITLE
setname with more than 8 chars

### ISSUE THREAD

**Issue by eubrunosilva** [sebdel/mra-tools-c#38]
Hi

there are some setnames with more than 8 chars. app is cutting the last chars but then some games have the same rom name.
it possible to cut the first chars?
Thanks

**Comment by sebdel** [comment]
I'll go with first 5 chars + 3 last chars to try to generate a unique file name.

**Comment by eubrunosilva** [comment]
thanks. I need this for robotron alternative version :) - at least
