### ISSUE TITLE
LF vs CRLF in windows

### ISSUE THREAD

**Issue by eubrunosilva** [sebdel/mra-tools-c#39]
in windows, we should have arc files with crlf and not lf

**Comment by sebdel** [comment]
Do you have a use case where it is a problem?
The most important thing is that the firmware parses the file just fine. 
There are also plenty of modern editors on windows that will open unix style files properly (notepad++, vscode...).

**Comment by eubrunosilva** [comment]
I'm using a lot the app (thanks for it) and i'm reporting all stuff I find :)
not all could be problems like this one.
I use notepad++ and i did even notice this before... only when I send arc file to a repo and git "told me this":

$ git add .
warning: LF will be replaced by CRLF in Arcade/Alien Arena.arc.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in Arcade/Amidar.arc.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in Arcade/Anteater.arc.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in Arcade/Armored Car.arc.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in Arcade/Battle of Atlantis.arc.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in Arcade/Bubbles.arc.

**Comment by sebdel** [comment]
That's interesting, actually there's a proper way to deal with that using .gitattributes apparently. I will add this to this repo:
```
*.mra         eol=lf
*.arc         eol=lf
*.sh          eol=lf
```

**Comment by eubrunosilva** [comment]
didn't know that also :)
closing "issue"
