### ISSUE TITLE
error: interleaved group width do not match total bytes in children patterns.

### ISSUE THREAD

**Issue by gyurco** [sebdel/mra-tools-c#57]
I'm not sure how to use the interleave correctly, but even the sampes/Spy Hunter.mra gives this message (and creates a wrong ROM)

**Comment by gyurco** [comment]
This XML snippet behaves wrongly:

      
      <interleave width="32">
          <part name="g-4c-a.bin" map="0001"/>
          <part name="g-4c-a.bin" map="0001"/>
          <part name="g-4c-a.bin" map="0001"/>
          <part name="g-4c-a.bin" map="0001"/>

          <part name="g-4d-a.bin" map="0010"/>
          <part name="g-4d-a.bin" map="0010"/>
          <part name="g-4d-a.bin" map="0010"/>
          <part name="g-4d-a.bin" map="0010"/>

          <part name="g-4e-a.bin" map="0100"/>
          <part name="g-4e-a.bin" map="0100"/>
          <part name="g-4e-a.bin" map="0100"/>
          <part name="g-4e-a.bin" map="0100"/>

          <part name="g-4e-a.bin" map="1000"/>
          <part name="g-4e-a.bin" map="1000"/>
          <part name="g-4e-a.bin" map="1000"/>
          <part name="g-4e-a.bin" map="1000"/>
      </interleave>

**Comment by sebdel** [comment]
FYI samples/ are examples of both working and not working files, for dev purpose. tests/ are more informatives.

I'll look into this snippet. It might be equivalent to that but I'm not sure. I need to check what happens when you use the same file at different position of the mapping:
```
  <interleave width="32">
      <part name="g-4c-a.bin" map="0001"/>
      <part name="g-4d-a.bin" map="0010"/>
      <part name="g-4e-a.bin" map="0100"/>
      <part name="g-4e-a.bin" map="1000"/>
  </interleave>
  <interleave width="32">
      <part name="g-4c-a.bin" map="0001"/>
      <part name="g-4d-a.bin" map="0010"/>
      <part name="g-4e-a.bin" map="0100"/>
      <part name="g-4e-a.bin" map="1000"/>
  </interleave>
  <interleave width="32">
      <part name="g-4c-a.bin" map="0001"/>
      <part name="g-4d-a.bin" map="0010"/>
      <part name="g-4e-a.bin" map="0100"/>
      <part name="g-4e-a.bin" map="1000"/>
  </interleave>
  <interleave width="32">
      <part name="g-4c-a.bin" map="0001"/>
      <part name="g-4d-a.bin" map="0010"/>
      <part name="g-4e-a.bin" map="0100"/>
      <part name="g-4e-a.bin" map="1000"/>
  </interleave>
```
you can also try to replace 
```
      <part name="g-4e-a.bin" map="0100"/>
      <part name="g-4e-a.bin" map="1000"/>
```
by
```
      <part name="g-4e-a.bin" map="2100"/>
```

**Comment by gyurco** [comment]
Thanks, that method worked, even without map.
https://github.com/gyurco/Mist_FPGA/blob/loderunner/Arcade_MiST/IremM62%20Hardware/meta/Lode%20Runner%202.mra#L40
So is it not possible to put more than one part in the same byte position in one group?

**Comment by sebdel** [comment]
Exactly. That's why \<group\> doesn't map 1:1 to \<interleave\>. That would need more work.

**Comment by gyurco** [comment]
Ah, ok, it's no problem for me. Just good to know.

**Comment by sorgelig** [comment]
Every new line with file means it started from beginning (if no offset specified). 
```
      <part name="g-4e-a.bin" map="0100"/>
      <part name="g-4e-a.bin" map="1000"/>
```
This means to load the same values into every 3rd and 4th bytes.

**Comment by sorgelig** [comment]
> So is it not possible to put more than one part in the same byte position in one group?

I'm not sure if i get the question right. For example if you have g-4c-a.bin twice bigger than g-4d-a.bin and g-4e-a.bin then write this:
```
  <interleave width="16">
      <part name="g-4c-a.bin" map="01"/>
      <part name="g-4d-a.bin" map="10"/>
      <part name="g-4e-a.bin" map="10"/>
  </interleave>
```
it will concatenate g-4d-a.bin and g-4e-a.bin in every second byte of result.

**Comment by sorgelig** [comment]
As for original question, it should work.
i use following in Spy Hunter:
```
		<interleave output="32">
			<part name="spy-hunter_video_1fg_11-18-83.a7" map="0001"/>
			<part name="spy-hunter_video_0fg_11-18-83.a8" map="0001"/>
			<part name="spy-hunter_video_3fg_11-18-83.a5" map="0010"/>
			<part name="spy-hunter_video_2fg_11-18-83.a6" map="0010"/>
			<part name="spy-hunter_video_5fg_11-18-83.a3" map="0100"/>
			<part name="spy-hunter_video_4fg_11-18-83.a4" map="0100"/>
			<part name="spy-hunter_video_7fg_11-18-83.a1" map="1000"/>
			<part name="spy-hunter_video_6fg_11-18-83.a2" map="1000"/>
		</interleave>
```
So it looks similar and it works fine. It doesn't matter if file name the same or different - it always treated as "other" file.
If it doesn't work, then it's a bug in mra-tools-c

**Comment by jotego** [comment]
How is the spy hunter one supposed to work? Does it read files a7, a5, a3 and a1 first and then continue with a8, a6, a4 and a2?

**Comment by sorgelig** [comment]
Right.
Interleave block sets the counters of each byte at the start position and it increased with every file in the same position till end of interleave block. Resulting size is counted by lower byte in case if counters will be different at the end.
