### ISSUE TITLE
ROM0 not found

### ISSUE THREAD

**Issue by manast** [sebdel/mra-tools-c#61]
Trying to use the tool but whatever .mra file I use I always get this error:

```bash
➜  ghouls git:(master) ✗ ../mra Ghouls\'n\ Ghosts\ -World-.mra
src/rom.c:299: error: ROM0 not found in MRA.
```

**Comment by jotego** [comment]
Need to pass the path to the ROM files.
mra file.mra -z pathtozip

**Comment by sebdel** [comment]
That error message is weird. It looks like it cannot find the rom tag with the index="0" attribute. I tried the mra with the same name from Jotego and it worked.
Can you double check the mra? Did you modify it maybe?

**Comment by manast** [comment]
@jotego same error:
![image](https://user-images.githubusercontent.com/95200/76260285-ba919000-6257-11ea-8485-244144a5d557.png)

@sebdel I compiled the tool in MacOS, could it be it is not compatible? btw, this is a 64bit only mac.

**Comment by jotego** [comment]
I think -z should point to the folder containing the zip file, not to the zip itself

**Comment by manast** [comment]
same problem: 
![image](https://user-images.githubusercontent.com/95200/76292008-a0cf6780-62ae-11ea-87a7-4da796077978.png)

**Comment by sebdel** [comment]
It's never been tested on MacOS. As far as I can tell there are problem with structure packing with various versions of gcc. That would need proper porting. What version of gcc are you using ?

**Comment by manast** [comment]
```bash
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
