### ISSUE TITLE
Pang! 3 MRA fails

### ISSUE THREAD

**Issue by jotego** [sebdel/mra-tools-c#73]
The length and size attributes are not being parsed correctly. This is needed for Pang! 3 GFX to load correctly. This is how it looks now.

![imagen](https://user-images.githubusercontent.com/1863036/81478696-3a6bb480-921f-11ea-958a-18788c52b316.png)

[Pang! 3 -Euro 950601-.mra.zip](https://github.com/sebdel/mra-tools-c/files/4604003/Pang.3.-Euro.950601-.mra.zip)

@sebdel , you can assign this issue to me.

**Comment by sebdel** [comment]
you just have to invert 2 lines to have the map pattern in the proper order:
```        <!-- gfx -->
        <interleave output="64">
            <part name="pa3-01m.2c" crc="068a152c" map="00000021" length="0x100000" offset="0"/>
            <part name="pa3-07m.2f" crc="3a4a619d" map="00002100" length="0x100000" offset="0"/>
            <part name="pa3-01m.2c" crc="068a152c" map="00210000" length="0x100000" offset="0x100000"/>
            <part name="pa3-07m.2f" crc="3a4a619d" map="21000000" length="0x100000" offset="0x100000"/>
        </interleave>
```

Amazing job by the way:
![pang3](https://user-images.githubusercontent.com/1623416/81496519-6f781580-92b8-11ea-96b8-a4b8b8794ef2.jpg)

**Comment by jotego** [comment]
We need a warning for that. I'm sure I'll forget again.

**Comment by sebdel** [comment]
I'm working on a patch to sort it at load time. That will be one less hassle.
