### ISSUE TITLE
Add support for config pages

### ISSUE THREAD

**Issue by gyurco** [sebdel/mra-tools-c#76]
In the next mist-firmware, a P config string option is added to define a new config page (as a submenu item).
There are two formats:
Px,Submenu
PxOyz,Menu Item
The former defines a new submenu, the other is just an ordinary option prefixed by the page.
This can be easily supported by two attributes in the **switches** element:
```
<switches page_name="Submenu" page_id="1">....</switches>
```
should generate:
```
P1,Submenu
P1Oxy,Ordinary options,a,b,c
```
If page_id is 0 (or omitted), then no change is necessary in the generated options.
if page_name is omitted, then no submenu option should be added.

Eventually more than one **switches** block can be also supported, each defining a different submenu. But not a high prio, especially for compatibility with the original. With one submenu, the separate OSD screen for the DIP switches can be easily achievable.

**Comment by sebdel** [comment]
I'll look into it. Would the order matter in case of multiple submenus ?

**Comment by gyurco** [comment]
If you're thinking about using separate switches block for each submenu, then I think the order should be the one in the MRA. Btw, the order only matters on the main page, where the option for opening the submenu is displayed.

**Comment by sebdel** [comment]
Can I close this or do you want to keep it open for "multiple switches" support?

**Comment by gyurco** [comment]
It can be closed, multiple switches support is not very important.
