### ISSUE TITLE
Changed DEFAULT value

### ISSUE THREAD

**Issue by gyurco** [sebdel/mra-tools-c#79]
I want to discuss the DEFAULT value change:
It was 0 (when it wasn't implemented), but it's 0xffffffff now. That might break some arcades in Gehstock's repo, where 0 was expected.
I think the DEFAULT value should be only written to the ARC file, when it's present in the MRA. Otherwise it should be left out. Please notice that the status bits are not just for DIP switches on MiST, but for every options.

**Comment by sebdel** [comment]
I think @jotego wrote it this way initially. I don't know if he expects that to be the default DEFAULT.
The CPS mras all have the default attribute. I think it's fine to change it.

**Comment by gyurco** [comment]
Yes, if there's a default value everywhere in his cores, then it shouldn't hurt if: default would be 0 instead of 0xffffff, and don't add DEFAULT= at all, if it's 0.

**Comment by gyurco** [comment]
Ooops, I see a strangeness: if there's default in the MRA, then the undefined bits still expected to be '1's.
