### ISSUE TITLE
Windows version makes wrong ROMs

### ISSUE THREAD

**Issue by gyurco** [sebdel/mra-tools-c#87]
Starting from the commit
7569ae9 (HEAD, origin/sort_interleaved_parts_by_map) Sort interleaved parts according to map
The Windows version creates bad ROMs.
Example:
https://github.com/gyurco/Mist_FPGA/blob/master/Arcade_MiST/Sega%20Zaxxon%20Hardware/Zaxxon_MiST/meta/Future%20Spy.mra
Compiling on Linux is OK.

**Comment by Gehstock** [comment]
[[URL=https://www.directupload.net/file/d/5940/ep97rpsm_png.htm][IMG]https://s12.directupload.net/images/200912/temp/ep97rpsm.png[/IMG][/URL]](url)

**Comment by sebdel** [comment]
Thanks for locating the bad commit. I'll look into it.

**Comment by gyurco** [comment]
Seems qsort on WIndows messes up the part order when map attribute is omitted (every map_index is 0).
